PACKAGE_NAME="cix-vpu-driver"
PACKAGE_VERSION="#MODULE_VERSION#"
BUILT_MODULE_NAME[0]="amvx"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates"
CLEAN="make clean"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_VIDEO_LINLON=m CONFIG_VIDEO_LINLON_MONO=y CONFIG_VIDEO_LINLON_IF_V4L2=y"
AUTOINSTALL=yes
